services:

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: metricmind-backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    volumes:
      - ../backend/uploads:/app/uploads
      - ../backend/cleaned:/app/cleaned
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: metricmind-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped